// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import Editora from '../Editora';
import Livro from '../Livro';
import { ControleEditoraService } from '../controle-editora.service';
import ControleLivrosService from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css',
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(
    servEditora: ControleEditoraService,
    servLivros: ControleLivrosService
  ) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    const obterTodos = async () => {
      try {
        await this.servLivros.obterLivros().then((dados) => {
          this.livros = dados;
        });
      } catch (err) {
        console.error('Error ao obter livros:', err);
      }
    };

    obterTodos();
  }

  excluir = (codigo: String) => {
    this.servLivros.excluir(codigo).then(async () => {
      try {
        await this.servLivros.obterLivros().then((dados) => {
          this.livros = dados;
        });
      } catch (err) {
        console.error('Error ao obter livros:', err);
      }
    });
  };

  obterNome = (codEditora: number) => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}

<main class="container">
  <h1 class="text-center py-4">Catálogo de Livros</h1>
  <table class="container-fluid">
    <thead>
      <tr class="text-light bg-dark col">
        <th class="p-3 col-2">Título</th>
        <th class="p-3 col-7">Resumo</th>
        <th class="p-3 col-1">Editora</th>
        <th class="p-3 col-2">Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>
          {{ livro.titulo }} <br>
          <button (click)="excluir(livro.codigo)" class="btn btn-danger">Excluir</button>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
  <h2 class="text-center py-5" *ngIf="livros.length <= 0">Estoque de livros vazio 😢</h2>
</main>

// clientes/livros-react/src/LivroLista.js
import ControleLivros from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";
import { useEffect, useState } from "react";

const controleLivro = new ControleLivros();
const controleEditora = new ControleEditora();

function LinhaLivro(props) {
  const { livro, excluir } = props;
  const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

  return (
    <tr>
      <td className='border-bottom text-center py-2'>
        {livro.titulo}
        <div>
          <button className="btn btn-danger" onClick={excluir}>
            Excluir
          </button>
        </div>
      </td>
      <td className='border-bottom py-2'>{livro.resumo}</td>
      <td className='border-bottom py-2 text-center'>{nomeEditora}</td>
      <td className='border-bottom py-2'>
        <ul>
          {livro.autores.map((autor, index) => {
            return <li key={index}>{autor}</li>;
          })}
        </ul>
      </td>
    </tr>
  );
}

export default function LivroLista() {
  const [livros, setLivros] = useState([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    const obterTodos = async () => {
      await controleLivro.obterLivros().then((res) => {
        setLivros(res);
      });
    };
    obterTodos();
    setCarregado(true);
  }, [carregado]);

  const excluir = (codigo) => {
    controleLivro.excluir(codigo).then(setCarregado(false));
  };

  return (
    <main className='container'>
      <h1 className='text-center py-4'>Catálogo de Livros</h1>
      <table className='container-fluid'>
        <thead>
          <tr className='text-light bg-dark col'>
            <th className='p-3 col-2 '>Título</th>
            <th className='p-3 col-7 '>Resumo</th>
            <th className='p-3 col-1 '>Editora</th>
            <th className='p-3 col-2 '>Autores</th>
          </tr>
        </thead>
        <tbody>
          {livros.map((livro, index) => (
            <LinhaLivro
              livro={livro}
              excluir={() => excluir(livro.codigo)}
              key={index}
            />
          ))}
        </tbody>
      </table>
      {livros.length <= 0 && (<h2 className='text-center py-5'>Estoque de livros vazio 😢</h2>)}
    </main>
  );
}
