// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import Editora from '../Editora';
import Livro from '../Livro';
import { ControleEditoraService } from '../controle-editora.service';
import ControleLivrosService from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css',
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  private servEditora: ControleEditoraService;
  private servLivros: ControleLivrosService;

  constructor(
    servEditora: ControleEditoraService,
    servLivros: ControleLivrosService
  ) {
    this.servEditora = servEditora;
    this.servLivros = servLivros;
  }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    const obterTodos = async () => {
      try {
        await this.servLivros.obterLivros().then((dados) => {
          this.livros = dados;
        });
      } catch (err) {
        console.error('Error ao obter livros:', err);
      }
    };

    obterTodos();
  }

  excluir = (codigo: String) => {
    this.servLivros.excluir(codigo).then(async () => {
      try {
        await this.servLivros.obterLivros().then((dados) => {
          this.livros = dados;
        });
      } catch (err) {
        console.error('Error ao obter livros:', err);
      }
    });
  };

  obterNome = (codEditora: number) => {
    return this.servEditora.getNomeEditora(codEditora);
  };
}

<main class="container">
  <h1 class="text-center py-4">Catálogo de Livros</h1>
  <table class="container-fluid">
    <thead>
      <tr class="text-light bg-dark col">
        <th class="p-3 col-2">Título</th>
        <th class="p-3 col-7">Resumo</th>
        <th class="p-3 col-1">Editora</th>
        <th class="p-3 col-2">Autores</th>
      </tr>
    </thead>
    <tbody>
      <tr *ngFor="let livro of livros">
        <td>
          {{ livro.titulo }} <br>
          <button (click)="excluir(livro.codigo)" class="btn btn-danger">Excluir</button>
        </td>
        <td>{{ livro.resumo }}</td>
        <td>{{ obterNome(livro.codEditora) }}</td>
        <td>
          <ul>
            <li *ngFor="let autor of livro.autores">{{ autor }}</li>
          </ul>
        </td>
      </tr>
    </tbody>
  </table>
  <h2 class="text-center py-5" *ngIf="livros.length <= 0">Estoque de livros vazio 😢</h2>
</main>

// clientes/livros-next/src/pages/LivroLista.tsx
import React, { useEffect, useState } from 'react';
import Head from 'next/head';
import { Menu } from '@/componente/Menu';
import {LinhaLivro} from '@/componente/LinhaLivro';
import Livro from '@/classes/modelo/Livro';
import styles from '../styles/Home.module.css'
import ControleLivro from '@/classes/controle/ControleLivros';

const baseURL = "http://localhost:3000/api/livros";

const controleLivros = new ControleLivro();

const LivroLista = () => {
  const [livros, setLivros] = useState<Livro[]>([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    const obterTodos = async () => {
      await controleLivros.obterLivros().then((resultado) => {
        setLivros(resultado)
      })
    };
    obterTodos();
    setCarregado(true)
  }, [carregado])

  const excluirLivro = async (codigo: String) => {
    const resposta = await fetch(`${baseURL}/${codigo}`, {
      method: 'DELETE'
    });
    return resposta.ok;
  }

  const excluir = (codigo: String) => {
    controleLivros.excluir(codigo).then(() => setCarregado(false));
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Loja Next</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Menu />
      <main className='container'>
      <h1 className='text-center py-4'>Livros</h1>
        <table className='container-fluid'>
        <thead>
          <tr className='text-light bg-dark col'>
            <th className='p-3 col-2 '>Título</th>
            <th className='p-3 col-7'>Resumo</th>
            <th className='p-3 col-1'>Editora</th>
            <th className='p-3 col-2'>Autores</th>
          </tr>
        </thead>
          <tbody>
            {livros.map((livro, index) => (
              <LinhaLivro
                key={index}
                livro={livro}
                excluir={() => excluir(livro.codigo)}
              />
            ))}
          </tbody>
        </table>
        {livros.length <= 0 ? (<h2 className='text-center py-5'>Estoque de livros vazio 😢</h2>) : (<></>)}
      </main>
    </div>
  );
};

export default LivroLista;
