// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import Livro from '../Livro';
import Editora from '../Editora';
import ControleLivrosService from '../controle-livros.service';
import { ControleEditoraService } from '../controle-editora.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css',
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro;
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  private router: Router;
  private servLivros: ControleLivrosService;
  private servEditora: ControleEditoraService;

  constructor(
    router: Router,
    servLivros: ControleLivrosService,
    servEditora: ControleEditoraService
  ) {
    this.livro = new Livro('', 0, '', '', []);
    this.router = router;
    this.servLivros = servLivros;
    this.servEditora = servEditora;
  }

  ngOnInit(): void {
    console.log(this.editoras);
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.livro.codEditora = Number(this.livro.codEditora);
    this.servLivros
      .incluir(this.livro)
      .then(() => this.router.navigateByUrl('/lista'));
  };
}

<main class="container p-3">
  <h1 class="my-4 text-center">Dados do Livro</h1>
  <form class="row col-6 mx-auto" (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título</label>
      <input
        type="text"
        class="form-control"
        id="titulo"
        name="titulo"
        [(ngModel)]="livro.titulo"
         required
      >
    </div>

    <div class="form-group">
      <label for="resumo">Resumo</label>
      <textarea
        class="form-control"
        id="resumo"
        name="resumo"
        [(ngModel)]="livro.resumo"
        required
      ></textarea>
    </div>

    <div class="form-group">
      <label for="editora">Editora</label>
      <select
        class="form-control form-control-md"
        id="editora"
        name="editora"
        [(ngModel)]="livro.codEditora"
        required
      >
        <option selected disabled>Selecione uma Editora</option>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>

    <div class="form-group">
      <label for="autores">Autores (1 por linha)</label>
      <textarea
        class="form-control"
        id="autores"
        name="autores"
        [(ngModel)]="autoresForm"
        required
      ></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-4">Incluir Livro</button>
  </form>
</main>

// clientes/livros-next/src/pages/LivroDados.tsx
import React from "react";
import { useRouter } from "next/router";
import { useState } from "react";
import ControleEditora from "@/classes/controle/ControleEditora";
import Livro from "@/classes/modelo/Livro";
import Head from "next/head";
import { Menu } from "@/componente/Menu";
import styles from '../styles/Home.module.css'
import ControleLivro from "@/classes/controle/ControleLivros";

const LivroDados = () => {
  const controleLivros = new ControleLivro();
  const controleEditora = new ControleEditora();

  const [codEditora, setCodEditora] = useState<number>(0);
  const [titulo, setTitulo] = useState("");
  const [resumo, setResumo] = useState("");
  const [autores, setAutores] = useState("");
  const navigate = useRouter().push;

  const opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora, 
    text: editora.nome
  }));

  function tratarCombo(event: React.ChangeEvent<HTMLSelectElement>) {
    setCodEditora(Number(event.target.value));
  }

  const incluir = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const livro = new Livro(
        '',
        codEditora,
        titulo,
        resumo,
        autores.split('\n'),
    );
    controleLivros.incluir(livro).then(() => navigate("/LivroLista"))
};

  return (
    <div className={styles.container}>
      <Head>
        <title>Novo Livro</title>
      </Head>

      <Menu />

      <main className={styles.main}>
        <h1 className='my-4 text-center'>Dados do Livro</h1>
        <form onSubmit={incluir} className="row col-6 mx-auto">
          <div className="form-group">
            <label htmlFor="titulo">Título:</label>
            <input 
              required 
              className="form-control" 
              id="titulo" 
              type="text" 
              value={titulo} 
              onChange={(event) => setTitulo(event.target.value)} 
            />
          </div>
          <div className="form-group">
            <label htmlFor="resumo">Resumo:</label>
            <textarea 
              required 
              id="resumo"
              className="form-control" 
              value={resumo} 
              onChange={(event) => setResumo(event.target.value)} 
            />
          </div>
          <div className="form-group">
            <label htmlFor="codEditora">Editora:</label>
            <select 
              required 
              id="codEditora" 
              className="form-control" 
              value={codEditora} 
              onChange={tratarCombo}
            >
              <option value="">Selecione</option>
              {opcoes.map((opcao) => (
                <option key={opcao.value} value={opcao.value}>
                  {opcao.text}
                </option>
              ))}
            </select>
          </div>
          <div className="form-group">
            <label htmlFor="autores">Autores:</label>
            <textarea 
              required 
              id="autores" 
              className="form-control" 
              value={autores} 
              onChange={(event) => setAutores(event.target.value)} 
            />
          </div>
          <button type="submit" className="btn btn-primary mt-4">Salvar Dados</button>
        </form>
    </main>
    </div>
  );
}

export default LivroDados;
