// clientes/livros-react/src/LivroDados.js
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import Livro from "./modelo/Livro";
import ControleLivro from "./controle/ControleLivros";
import ControleEditora from "./controle/ControleEditora";

const controleLivro = new ControleLivro();
const controleEditora = new ControleEditora();

export default function LivroDados() {
  const opcoes = controleEditora.getEditoras().map((editora) => ({
    value: editora.codEditora,
    text: editora.nome,
  }));

  const [titulo, setTitulo] = useState(String);
  const [resumo, setResumo] = useState(String);
  const [autores, setAutores] = useState(String);
  const [codEditora, setCodEditora] = useState(0);

  const navigate = useNavigate();

  const tratarCombo = (e) => {
    setCodEditora(Number(e.target.value));
  };

  const incluir = (e) => {
    e.preventDefault();

    const novoLivro = new Livro();

    novoLivro.codEditora = codEditora;
    novoLivro.titulo = titulo;
    novoLivro.resumo = resumo;
    novoLivro.autores = autores.split("\n");

    controleLivro.incluir(novoLivro).then(() => navigate("/"))
  };

  return (
    <main>
        <h1 className="my-4 text-center">Dados do Livro</h1>
        <form className="row col-6 mx-auto" onSubmit={(e) => incluir(e)}>
          <div className="form-group">
            <label htmlFor="titulo">Título</label>
              <input
                required
                className="form-control"
                id="titulo"
                name="titulo"
                type="text"
                onChange={(e) => setTitulo(e.target.value)}
              />
          </div>
          <div className="form-group">
            <label htmlFor="resumo">Resumo</label>
              <textarea
                required
                className="form-control"
                id="resumo"
                onChange={(e) => setResumo(e.target.value)}
              />
          </div>
          <div className="form-group">
            <label htmlFor="editora">Editora</label>
              <select
                required
                className="form-control form-control-md"
                id="editora"
                onChange={(e) => tratarCombo(e)}
              >
                {opcoes.map((opcao, index) => (
                  <option key={index} value={opcao.value}>
                    {opcao.text}
                  </option>
                ))}
              </select>
          </div>
          <div className="form-group">
            <label htmlFor="autores">Autores (1 por linha)</label>
              <textarea
                required
                className="form-control"
                id="autores"
                onChange={(e) => setAutores(e.target.value)}
              />
          </div>
            <button className="btn btn-primary mt-4" type="submit" >Salvar Dados</button>
        </form>
    </main>
  );
}

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import Livro from '../Livro';
import Editora from '../Editora';
import ControleLivrosService from '../controle-livros.service';
import { ControleEditoraService } from '../controle-editora.service';
import { Router } from '@angular/router';

@Component({
  selector: 'app-livro-dados',
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css',
})
export class LivroDadosComponent implements OnInit {
  public livro: Livro;
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  private router: Router;
  private servLivros: ControleLivrosService;
  private servEditora: ControleEditoraService;

  constructor(
    router: Router,
    servLivros: ControleLivrosService,
    servEditora: ControleEditoraService
  ) {
    this.livro = new Livro('', 0, '', '', []);
    this.router = router;
    this.servLivros = servLivros;
    this.servEditora = servEditora;
  }

  ngOnInit(): void {
    console.log(this.editoras);
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = () => {
    this.livro.autores = this.autoresForm.split('\n');
    this.livro.codEditora = Number(this.livro.codEditora);
    this.servLivros
      .incluir(this.livro)
      .then(() => this.router.navigateByUrl('/lista'));
  };
}

<main class="container p-3">
  <h1 class="my-4 text-center">Dados do Livro</h1>
  <form class="row col-6 mx-auto" (submit)="incluir()" ngNativeValidate>
    <div class="form-group">
      <label for="titulo">Título</label>
      <input
        type="text"
        class="form-control"
        id="titulo"
        name="titulo"
        [(ngModel)]="livro.titulo"
         required
      >
    </div>

    <div class="form-group">
      <label for="resumo">Resumo</label>
      <textarea
        class="form-control"
        id="resumo"
        name="resumo"
        [(ngModel)]="livro.resumo"
        required
      ></textarea>
    </div>

    <div class="form-group">
      <label for="editora">Editora</label>
      <select
        class="form-control form-control-md"
        id="editora"
        name="editora"
        [(ngModel)]="livro.codEditora"
        required
      >
        <option selected disabled>Selecione uma Editora</option>
        <option *ngFor="let editora of editoras" [value]="editora.codEditora">{{ editora.nome }}</option>
      </select>
    </div>

    <div class="form-group">
      <label for="autores">Autores (1 por linha)</label>
      <textarea
        class="form-control"
        id="autores"
        name="autores"
        [(ngModel)]="autoresForm"
        required
      ></textarea>
    </div>

    <button type="submit" class="btn btn-primary mt-4">Incluir Livro</button>
  </form>
</main>
